from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from pathlib import Path
from typing import Dict, Iterable, Tuple

import requests

from config import load_env


load_env()


def _build_fallback_email_body(violation_types: Iterable[str], timestamp: str, counts: Dict[str, int]) -> str:
    violations = ", ".join(violation_types) or "Traffic rule violation"
    no_helmet = counts.get("No Helmet", 0)
    triple_riding = counts.get("Triple Riding", 0)
    total_rule_violations = counts.get("Traffic Rule Violation", 0)

    return (
        "Dear Traffic Monitoring Officer,\n\n"
        "This is an automated incident notification generated by the AI Traffic Violation Detection System.\n\n"
        f"Incident timestamp: {timestamp}\n"
        f"Observed violation categories: {violations}\n"
        f"No-helmet detections: {no_helmet}\n"
        f"Triple-riding detections: {triple_riding}\n"
        f"Traffic rule violation events: {total_rule_violations}\n\n"
        "The attached image contains the captured evidence frame from the processed video. "
        "Kindly review the incident details and take the necessary action as per applicable traffic enforcement procedure.\n\n"
        "Regards,\n"
        "AI Traffic Violation Detection System"
    )


def generate_email_body(violation_types: Iterable[str], timestamp: str, counts: Dict[str, int]) -> str:
    violations = ", ".join(violation_types) or "Traffic rule violation"
    groq_api_key = os.getenv("GROQ_API_KEY")
    groq_model = os.getenv("GROQ_MODEL", "llama3-8b-8192")

    if not groq_api_key:
        return _build_fallback_email_body(violation_types, timestamp, counts)

    payload = {
        "model": groq_model,
        "messages": [
            {
                "role": "system",
                "content": "Write realistic, formal traffic enforcement alert emails with concise operational language.",
            },
            {
                "role": "user",
                "content": (
                    "Generate a realistic professional email body for a traffic monitoring system. "
                    f"Violation type(s): {violations}. Timestamp: {timestamp}. "
                    f"No Helmet count: {counts.get('No Helmet', 0)}. "
                    f"Triple Riding count: {counts.get('Triple Riding', 0)}. "
                    f"Traffic Rule Violation count: {counts.get('Traffic Rule Violation', 0)}. "
                    "Use a formal official tone, mention that the attached image is evidence, and keep it clear and believable."
                ),
            },
        ],
        "temperature": 0.4,
    }

    try:
        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {groq_api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=20,
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"].strip()
    except Exception:
        return _build_fallback_email_body(violation_types, timestamp, counts)


def send_violation_alert(
    violation_types: Iterable[str],
    timestamp: str,
    image_path: str,
    counts: Dict[str, int],
) -> Tuple[bool, str]:
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    sender_email = os.getenv("SENDER_EMAIL")
    smtp_user = os.getenv("SMTP_USER", sender_email or "")
    smtp_password = os.getenv("SMTP_PASSWORD") or os.getenv("SENDER_PASSWORD")
    receiver_email = os.getenv("RECEIVER_EMAIL")

    if smtp_password:
        smtp_password = smtp_password.replace(" ", "").strip()

    if not all([smtp_server, smtp_user, smtp_password, receiver_email]):
        reason = "Missing SMTP configuration."
        print(f"Email alert skipped: {reason}")
        return False, reason

    body = generate_email_body(violation_types, timestamp, counts)
    message = EmailMessage()
    message["Subject"] = (
        "Traffic Violation Alert | "
        f"No Helmet: {counts.get('No Helmet', 0)} | "
        f"Triple Riding: {counts.get('Triple Riding', 0)} | "
        f"Rule Violations: {counts.get('Traffic Rule Violation', 0)}"
    )
    message["From"] = sender_email
    message["To"] = receiver_email
    message.set_content(body)

    image_file = Path(image_path) if image_path else None
    if image_file and image_file.is_file():
        with image_file.open("rb") as file:
            image_data = file.read()
        message.add_attachment(
            image_data,
            maintype="image",
            subtype="jpeg",
            filename=image_file.name,
        )

    try:
        with smtplib.SMTP(smtp_server, smtp_port, timeout=20) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(message)
        print(f"Email alert sent successfully to {receiver_email}.")
        return True, f"Alert email sent successfully to {receiver_email}."
    except Exception as exc:
        print(f"Email alert failed: {exc}")
        return False, str(exc)
